import { makeT } from '../../../shared/i18n.js';

export const tr = makeT({
  en: {
    score: 'SCORE',
    moves: 'MOVES',
    misses: 'MISSES LEFT',
    chooseMode: 'Choose a mode',
    'mode.classic': 'Classic',
    'mode.classic.about': 'Every swap costs a move. Specials and long chains earn moves back.',
    'mode.zen': 'Zen',
    'mode.zen.about': 'Only swaps that make no match cost a move. Play as long as you like.',
    bonusMoves: '+{n} moves',
    shuffling: 'No moves - shuffling!',
    'bomb.name': 'Bomb',
    'bomb.how': 'Match 4 in a row',
    'bomb.does': 'Clears the 3×3 square around it.',
    'cross.name': 'Cross',
    'cross.how': 'Match in an L or T shape',
    'cross.does': 'Clears its whole row and column.',
    'rainbow.name': 'Rainbow',
    'rainbow.how': 'Match 5 in a row',
    'rainbow.does': 'Swap it with a potion to clear every potion of that colour.',
  },
  sv: {
    score: 'POÄNG',
    moves: 'DRAG',
    misses: 'MISSAR KVAR',
    chooseMode: 'Välj läge',
    'mode.classic': 'Klassiskt',
    'mode.classic.about': 'Varje byte kostar ett drag. Specialdrycker och långa kedjor ger drag tillbaka.',
    'mode.zen': 'Zen',
    'mode.zen.about': 'Bara byten som inte ger en matchning kostar ett drag. Spela så länge du vill.',
    bonusMoves: '+{n} drag',
    shuffling: 'Inga drag – blandar!',
    'bomb.name': 'Bomb',
    'bomb.how': 'Matcha 4 i rad',
    'bomb.does': 'Rensar rutorna 3×3 runt den.',
    'cross.name': 'Kors',
    'cross.how': 'Matcha i en L- eller T-form',
    'cross.does': 'Rensar hela sin rad och kolumn.',
    'rainbow.name': 'Regnbåge',
    'rainbow.how': 'Matcha 5 i rad',
    'rainbow.does': 'Byt den med en dryck för att rensa alla drycker i den färgen.',
  },
});
