import { makeT } from '../../../shared/i18n.js';

export const tr = makeT({
  en: {
    bait: 'Bait {n}/{max}',
    book: 'Book {n}/{max}',
    breed: 'Breed',
    release: 'Release',
    fish: 'Fish',
    bookButton: 'Book',
    unit: 'Book entries',
    hintPick: 'Tap two grown-up creatures to breed them.',
    hintSecond: 'Tap a second creature to breed with it.',
    baby: 'Baby: grows up in {s} s',
    resting: 'Resting for {s} s',
    ready: 'Ready to breed',
    from: 'from {name}',
    wild: 'wild',
    bred: 'bred here',
    pairReady: 'Tap Breed to breed these two.',
    pairNotReady: 'Both need to be grown up and rested.',
    pondFull: 'The pond is full. Release a creature to make room.',
    noBait: 'No bait left. You get one back every 10 minutes, or one for each creature you release.',
    releaseTitle: 'Release it?',
    releaseMessage: 'It swims off into the shared pond, where another player may catch it. You get a bait back.',
    releaseYes: 'Release',
    lastOnes: 'Keep at least two creatures so you can breed.',
    caughtFrom: 'You caught a creature released by {name}!',
    caughtWild: 'A wild creature bit!',
    newEntry: 'New in your book: {name}',
    firstEver: 'You are the first player to find {name}!',
    firstBy: '{name} was first found by {who}',
    bookTitle: 'Collection book',
    bookIntro: 'Every body, colour, pattern and feature you have seen in your pond. ★ marks rare ones, which only appear when a creature is born with a mutation.',
    bookFirst: 'first: {name}',
    bookUnknown: '?',
    offline: 'Couldn’t reach the shared pond. Try again when you’re online.',
    trait_body: 'Body',
    trait_colour: 'Colour',
    trait_pattern: 'Pattern',
    trait_fins: 'Fins',
    trait_eyes: 'Eyes',
    trait_crest: 'Head',
    trait_glow: 'Glow',
    'body:round': 'Round',
    'body:long': 'Long',
    'body:drop': 'Drop',
    'body:puff': 'Spiky',
    'body:star': 'Star',
    'colour:coral': 'Coral',
    'colour:sun': 'Sun',
    'colour:leaf': 'Leaf',
    'colour:sea': 'Sea',
    'colour:violet': 'Violet',
    'colour:rose': 'Rose',
    'colour:frost': 'Frost',
    'colour:ember': 'Ember',
    'colour:night': 'Night',
    'pattern:plain': 'Plain',
    'pattern:spots': 'Spots',
    'pattern:stripes': 'Stripes',
    'pattern:patches': 'Patches',
    'pattern:sparkles': 'Sparkles',
    'fins:small': 'Small fins',
    'fins:frills': 'Frills',
    'fins:whiskers': 'Whiskers',
    'fins:wings': 'Wings',
    'eyes:two': 'Two eyes',
    'eyes:one': 'One eye',
    'eyes:three': 'Three eyes',
    'crest:none': 'Bare head',
    'crest:antennae': 'Antennae',
    'crest:horns': 'Horns',
    'crest:crown': 'Crown',
    'glow:none': 'No glow',
    'glow:glow': 'Glowing',
  },
  sv: {
    bait: 'Bete {n}/{max}',
    book: 'Bok {n}/{max}',
    breed: 'Para',
    release: 'Släpp',
    fish: 'Fiska',
    bookButton: 'Bok',
    unit: 'Bokposter',
    hintPick: 'Tryck på två vuxna varelser för att para dem.',
    hintSecond: 'Tryck på en varelse till för att para dem.',
    baby: 'Unge: vuxen om {s} s',
    resting: 'Vilar i {s} s',
    ready: 'Redo att para sig',
    from: 'från {name}',
    wild: 'vild',
    bred: 'född här',
    pairReady: 'Tryck på Para för att para de här två.',
    pairNotReady: 'Båda måste vara vuxna och utvilade.',
    pondFull: 'Dammen är full. Släpp en varelse för att göra plats.',
    noBait: 'Betet är slut. Du får tillbaka ett var tionde minut, eller ett för varje varelse du släpper.',
    releaseTitle: 'Släppa den?',
    releaseMessage: 'Den simmar ut i den gemensamma dammen, där en annan spelare kan fånga den. Du får tillbaka ett bete.',
    releaseYes: 'Släpp',
    lastOnes: 'Behåll minst två varelser så att du kan para dem.',
    caughtFrom: 'Du fångade en varelse som {name} släppte!',
    caughtWild: 'En vild varelse nappade!',
    newEntry: 'Nytt i boken: {name}',
    firstEver: 'Du är den första spelaren som hittat {name}!',
    firstBy: '{name} hittades först av {who}',
    bookTitle: 'Samlarbok',
    bookIntro: 'Alla kroppar, färger, mönster och drag du har sett i din damm. ★ betyder sällsynt: de dyker bara upp när en varelse föds med en mutation.',
    bookFirst: 'först: {name}',
    bookUnknown: '?',
    offline: 'Kunde inte nå den gemensamma dammen. Försök igen när du är uppkopplad.',
    trait_body: 'Kropp',
    trait_colour: 'Färg',
    trait_pattern: 'Mönster',
    trait_fins: 'Fenor',
    trait_eyes: 'Ögon',
    trait_crest: 'Huvud',
    trait_glow: 'Sken',
    'body:round': 'Rund',
    'body:long': 'Lång',
    'body:drop': 'Droppe',
    'body:puff': 'Taggig',
    'body:star': 'Stjärna',
    'colour:coral': 'Korall',
    'colour:sun': 'Sol',
    'colour:leaf': 'Löv',
    'colour:sea': 'Hav',
    'colour:violet': 'Viol',
    'colour:rose': 'Ros',
    'colour:frost': 'Frost',
    'colour:ember': 'Glöd',
    'colour:night': 'Natt',
    'pattern:plain': 'Enfärgad',
    'pattern:spots': 'Prickar',
    'pattern:stripes': 'Ränder',
    'pattern:patches': 'Fläckar',
    'pattern:sparkles': 'Glitter',
    'fins:small': 'Små fenor',
    'fins:frills': 'Volanger',
    'fins:whiskers': 'Morrhår',
    'fins:wings': 'Vingar',
    'eyes:two': 'Två ögon',
    'eyes:one': 'Ett öga',
    'eyes:three': 'Tre ögon',
    'crest:none': 'Kal hjässa',
    'crest:antennae': 'Antenner',
    'crest:horns': 'Horn',
    'crest:crown': 'Krona',
    'glow:none': 'Inget sken',
    'glow:glow': 'Lysande',
  },
});
