import { makeT } from '../../../shared/i18n.js';

export const tr = makeT({
  en: {
    brewTab: 'Brew',
    buyTab: 'Buy',
    sellTab: 'Sell',
    unit: 'Gold earned',
    gold: '{n}',
    empty: 'Empty',
    brew: 'Brew',
    learn: 'Learn {price}',
    learnTitle: 'Learn {name}?',
    learnMessage: 'The recipe costs {price} gold. It sells for about {value} gold a potion.',
    learnYes: 'Learn it',
    tooPoor: 'Not enough gold.',
    stock: 'In stock: {n}',
    match: 'Match {n}%',
    noMatch: 'Not a match yet',
    makes: 'Makes {n}',
    pickRecipe: 'Pick a recipe, then add ingredients until the balance matches.',
    cauldronFull: 'The cauldron is full.',
    noneLeft: 'You have none left. Buy more at the market.',
    brewed: 'Brewed {n} × {name}!',
    firstBrewedBy: 'First ever brewed by {name}',
    firstEver: 'You are the first player to brew {name}!',
    merchantHello: 'Fresh stock today. Tap to buy one. Tomorrow brings new wares and prices.',
    owned: 'Have {n}',
    merchantBuyBack: 'I\u2019ll take ingredients back for half the usual price. Tap to sell one.',
    sellBackMode: 'Sell back',
    buyMode: 'Buy',
    nothingToSellBack: 'You have no ingredients to sell.',
    bought: '−{price}',
    hot: 'In demand today: {name}',
    sellAll: 'Sell {n}',
    nothingToSell: 'Brew some first.',
    sold: '+{n} gold',
    quality: '{n}% quality',
    offline: 'Offline: local market prices.',
    marketBusy: 'The market is busy. Try again in a moment.',
    pity: '{name} takes pity on you: here are {n} gold to start again.',
    ignis: 'Fire',
    aqua: 'Water',
    terra: 'Earth',
    aer: 'Air',
    umbra: 'Shadow',
    vessa: 'Vessa',
    bramm: 'Bramm',
    hesk: 'Hesk',
    healthTonic: 'Health Tonic',
    emberDraught: 'Ember Draught',
    sunfireTincture: 'Sunfire Tincture',
    ironskinSalve: 'Ironskin Salve',
    deepwaterCordial: 'Deepwater Cordial',
    windDraught: 'Wind Draught',
    mirebloomElixir: 'Mirebloom Elixir',
    featherstoneDraught: 'Featherstone Draught',
    stormfireFlask: 'Stormfire Flask',
    shadowPhiltre: 'Shadow Philtre',
    nightGlass: 'Night Glass',
    wraithwindVial: 'Wraithwind Vial',
    pepper: 'Pepper',
    emberroot: 'Emberroot',
    bluepetal: 'Bluepetal',
    dewcap: 'Dewcap',
    moonpetal: 'Moonpetal',
    broadleaf: 'Broadleaf',
    barrowAsh: 'Barrow Ash',
    galeThistle: 'Gale Thistle',
    ashfern: 'Ashfern',
    violetUmbrella: 'Violet Umbrella',
    roseSalt: 'Rose Salt',
    nullstone: 'Nullstone',
  },
  sv: {
    brewTab: 'Brygg',
    buyTab: 'Köp',
    sellTab: 'Sälj',
    unit: 'Intjänat guld',
    gold: '{n}',
    empty: 'Töm',
    brew: 'Brygg',
    learn: 'Lär {price}',
    learnTitle: 'Lära dig {name}?',
    learnMessage: 'Receptet kostar {price} guld. Det säljs för ungefär {value} guld per dryck.',
    learnYes: 'Lär dig',
    tooPoor: 'Du har inte tillräckligt med guld.',
    stock: 'I lager: {n}',
    match: 'Träff {n}%',
    noMatch: 'Ingen träff än',
    makes: 'Blir {n}',
    pickRecipe: 'Välj ett recept och lägg i ingredienser tills balansen stämmer.',
    cauldronFull: 'Kitteln är full.',
    noneLeft: 'Du har inga kvar. Köp fler på marknaden.',
    brewed: 'Du bryggde {n} × {name}!',
    firstBrewedBy: 'Bryggdes först av {name}',
    firstEver: 'Du är den första spelaren som bryggt {name}!',
    merchantHello: 'Nya varor i dag. Tryck för att köpa en. I morgon kommer nya varor och priser.',
    owned: 'Har {n}',
    merchantBuyBack: 'Jag tar tillbaka ingredienser för halva det vanliga priset. Tryck för att sälja en.',
    sellBackMode: 'Sälj tillbaka',
    buyMode: 'Köp',
    nothingToSellBack: 'Du har inga ingredienser att sälja.',
    bought: '−{price}',
    hot: 'Efterfrågat i dag: {name}',
    sellAll: 'Sälj {n}',
    nothingToSell: 'Brygg några först.',
    sold: '+{n} guld',
    quality: '{n}% kvalitet',
    offline: 'Offline: lokala marknadspriser.',
    marketBusy: 'Marknaden har fullt upp. Försök igen om en stund.',
    pity: '{name} tycker synd om dig: här är {n} guld så att du kan börja om.',
    ignis: 'Eld',
    aqua: 'Vatten',
    terra: 'Jord',
    aer: 'Luft',
    umbra: 'Skugga',
    vessa: 'Vessa',
    bramm: 'Bramm',
    hesk: 'Hesk',
    healthTonic: 'Hälsotonikum',
    emberDraught: 'Glödbrygd',
    sunfireTincture: 'Soleldstinktur',
    ironskinSalve: 'Järnhudssalva',
    deepwaterCordial: 'Djupvattenlikör',
    windDraught: 'Vindbrygd',
    mirebloomElixir: 'Myrblomselixir',
    featherstoneDraught: 'Fjäderstensbrygd',
    stormfireFlask: 'Stormeldsflaska',
    shadowPhiltre: 'Skuggdekokt',
    nightGlass: 'Nattglas',
    wraithwindVial: 'Vålnadsvindsflaska',
    pepper: 'Peppar',
    emberroot: 'Glödrot',
    bluepetal: 'Blåblad',
    dewcap: 'Daggskivling',
    moonpetal: 'Månblad',
    broadleaf: 'Bredblad',
    barrowAsh: 'Gravaska',
    galeThistle: 'Stormtistel',
    ashfern: 'Askbräken',
    violetUmbrella: 'Violparaply',
    roseSalt: 'Rossalt',
    nullstone: 'Nollsten',
  },
});
