import { makeT } from '../../../shared/i18n.js';

// The game's own text, in every language.
export const tr = makeT({
  en: {
    wave: 'Wave {wave}',
    'depth.adventurers': 'Adventurers',
    'depth.holy': 'Holy army',
    'depth.demons': 'Rival demons',
    lord: 'Demon lord',
    lordLevel: 'Lv {level}',
    next: 'Next wave ▶',
    boss: 'Boss wave!',
    bossAt: 'Boss at wave {wave}',
    fell: 'The demon lord fell! Back to wave {wave}.',
    wallBroken: 'The wall is broken!',
    wallRebuilt: 'The wall stands again.',
    levelUp: 'Demon lord level {level}!',
    runeFound: 'Rune found: {rune}',
    unlocked: 'New: {what}',
    'tab.battle': 'Battle',
    'tab.lord': 'Lord',
    'tab.monsters': 'Monsters',
    'tab.spells': 'Spells',
    'tab.runes': 'Runes',
    'tab.build': 'Build',
    hp: 'Health',
    dmg: 'Damage',
    xp: 'XP',
    level: 'Level {level}',
    wallHp: 'Wall',
    noWallYet: 'No wall yet',
    rebuilding: 'Rebuilding {seconds} s',
    bestWave: 'Best wave: {wave}',
    heroesLeft: 'Heroes left: {n}',
    perHour: 'At this wave: {souls} souls per hour',
    nextHint: 'Clear this wave once to go on. Cleared waves repeat until you tap Next wave.',
    recruit: 'Recruit',
    upgrade: 'Upgrade',
    upgradeTo: 'Upgrade to {level}',
    place: 'Place',
    move: 'Move',
    store: 'Store',
    buy: 'Buy',
    build: 'Build',
    cancel: 'Cancel',
    close: 'Close',
    locked: 'Lord level {level}',
    stored: 'In the inventory',
    deployed: 'Deployed',
    dead: 'Returns next wave',
    army: 'Your monsters',
    shop: 'Recruit',
    slots: 'Slots',
    slotsOf: '{kind}: {used} / {max}',
    buySlot: '+1 slot',
    'kind.melee': 'Melee',
    'kind.ranged': 'Ranged',
    'kind.wall': 'On the wall',
    'kind.support': 'Behind the wall',
    'kind.trap': 'Traps',
    placeHint: 'Tap a glowing cell to place {name}.',
    aimHint: 'Tap where Hellfire should land.',
    cell: 'Row {row}: {kind}',
    emptyCell: 'Nothing here yet.',
    fits: 'Put here',
    'problem.slots': 'No free slot: buy another in {tab}.',
    'problem.noWall': 'Build the wall first.',
    'problem.taken': 'Something is already there.',
    'problem.souls': 'Not enough souls.',
    'm.orc': 'Orc warrior',
    'm.ogre': 'Ogre',
    'm.imp': 'Imp',
    'm.skeleton': 'Skeleton archer',
    'm.shaman': 'Orc shaman',
    'm.necro': 'Necromancer',
    'md.orc': 'Melee, all-round.',
    'md.ogre': 'Melee tank, hits 2 heroes.',
    'md.imp': 'Melee, very fast attacks.',
    'md.skeleton': 'Ranged, long reach.',
    'md.shaman': 'Ranged magic, slows heroes.',
    'md.necro': 'Ranged, hits around the target.',
    's.ballista': 'Bone ballista',
    's.brazier': 'Hellfire brazier',
    's.turret': 'Soul turret',
    's.altar': 'Blood altar',
    's.drum': 'War drum',
    's.well': 'Soul well',
    's.spikes': 'Spike pit',
    's.tar': 'Tar pool',
    's.bones': 'Bone spikes',
    'sd.ballista': 'Long-range bolts at one hero.',
    'sd.brazier': 'Burns heroes in a small area.',
    'sd.turret': 'A soul bolt that jumps to 3 heroes.',
    'sd.altar': 'Heals the wall and monsters.',
    'sd.drum': '+{n}% damage for your whole side.',
    'sd.well': '+{n}% souls from kills.',
    'sd.spikes': 'Hurts each hero that crosses.',
    'sd.tar': 'Heroes on it move {n}% slower.',
    'sd.bones': 'Stops each hero for {n} s.',
    wall: 'The wall',
    wallAbout: 'Holds heroes back. Ranged monsters on it add to its health. A broken wall rebuilds itself in {n} s.',
    buildWall: 'Build the wall',
    structures: 'Structures',
    owned: 'Yours',
    'sp.hellfire': 'Hellfire',
    'sp.bonewall': 'Bone wall',
    'sp.souldrain': 'Soul drain',
    'spd.hellfire': 'Burns every hero where you tap.',
    'spd.bonewall': 'Shields the wall and front line.',
    'spd.souldrain': 'Drains 3 heroes and heals your side.',
    cast: 'Cast',
    ready: 'Ready',
    autoCast: 'Auto-cast',
    on: 'On',
    off: 'Off',
    'r.fury': 'Fury',
    'r.vigor': 'Vigor',
    'r.haste': 'Haste',
    'r.leech': 'Leech',
    'r.greed': 'Greed',
    'r.thorns': 'Thorns',
    'rd.fury': '+{n}% damage',
    'rd.vigor': '+{n}% health',
    'rd.haste': '+{n}% attack speed',
    'rd.leech': 'Heals {n}% of damage dealt',
    'rd.greed': '+{n}% souls (anywhere)',
    'rd.thorns': 'Reflects {n}% of melee damage',
    'rarity.0': 'Common',
    'rarity.1': 'Rare',
    'rarity.2': 'Epic',
    'rarity.3': 'Legendary',
    'rarity.4': 'Mythic',
    runeName: '{rarity} {type}',
    merge: 'Merge 3',
    breakDown: 'Break (+{souls})',
    noRunes: 'No runes yet. Heroes sometimes drop them, and bosses always do.',
    runeSlots: 'Runes',
    runeSlotLocked: 'Opens at level {level}',
    emptySlot: 'Empty',
    chooseRune: 'Choose a rune',
    unequip: 'Take off',
    equippedOn: 'On: {who}',
    learn: 'Learn',
    tapTalent: 'Tap a talent to see what it does.',
    inventory: 'Inventory',
    'ts.lordDmg': 'Lord damage',
    'ts.cooldown': 'Cooldowns',
    'ts.burn': 'Burning ground',
    'ts.bossReset': 'Boss reset',
    'ts.monsterHp': 'Monster health',
    'ts.monsterDmg': 'Monster damage',
    'ts.recruitCost': 'Cheap recruits',
    'ts.slotCost': 'Cheap slots',
    'ts.souls': 'More souls',
    'ts.runeDrop': 'Rune drops',
    'ts.offline': 'Away time',
    'ts.mergeRefund': 'Merge refund',
    'ts.wallHp': 'Wall health',
    'ts.rebuild': 'Fast rebuild',
    'ts.structCost': 'Cheap building',
    'ts.trapDmg': 'Trap damage',
    talents: 'Talents',
    points: 'Points: {n}',
    'b.tyranny': 'Tyranny',
    'b.legion': 'Legion',
    'b.greed': 'Greed',
    'b.fortress': 'Fortress',
    't.lordDmg': '+5% lord damage',
    't.cooldown': '−5% spell cooldowns',
    't.burn': 'Hellfire leaves burning ground',
    't.bossReset': 'Boss kills reset spell cooldowns',
    't.monsterHp': '+5% monster health',
    't.monsterDmg': '+5% monster damage',
    't.recruitCost': '−10% recruit and upgrade cost',
    't.slotCost': '−20% slot cost',
    't.souls': '+5% souls',
    't.runeDrop': '+1% rune drop chance',
    't.offline': '+2 h offline limit',
    't.mergeRefund': 'Merging sometimes refunds a rune',
    't.wallHp': '+8% wall health',
    't.rebuild': '−10% wall rebuild time',
    't.structCost': '−10% structure cost',
    't.trapDmg': 'Traps hit 50% harder',
    away: 'While you were away',
    awayText: 'Your monsters held wave {wave} for {time}.',
    awaySouls: '+{n} souls',
    awayXp: '+{n} XP',
    awayRunes: '+{n} runes',
    awayLevels: 'The demon lord gained {n} levels.',
    hours: '{h} h {m} min',
    minutes: '{m} min',
  },
  sv: {
    wave: 'Våg {wave}',
    'depth.adventurers': 'Äventyrare',
    'depth.holy': 'Heliga hären',
    'depth.demons': 'Rivaliserande demoner',
    lord: 'Demonfursten',
    lordLevel: 'Nivå {level}',
    next: 'Nästa våg ▶',
    boss: 'Bossvåg!',
    bossAt: 'Boss vid våg {wave}',
    fell: 'Demonfursten föll! Tillbaka till våg {wave}.',
    wallBroken: 'Muren är raserad!',
    wallRebuilt: 'Muren står igen.',
    levelUp: 'Demonfursten nivå {level}!',
    runeFound: 'Runa hittad: {rune}',
    unlocked: 'Nytt: {what}',
    'tab.battle': 'Strid',
    'tab.lord': 'Fursten',
    'tab.monsters': 'Monster',
    'tab.spells': 'Besvärjelser',
    'tab.runes': 'Runor',
    'tab.build': 'Bygg',
    hp: 'Hälsa',
    dmg: 'Skada',
    xp: 'XP',
    level: 'Nivå {level}',
    wallHp: 'Mur',
    noWallYet: 'Ingen mur än',
    rebuilding: 'Byggs upp {seconds} s',
    bestWave: 'Bästa våg: {wave}',
    heroesLeft: 'Hjältar kvar: {n}',
    perHour: 'På den här vågen: {souls} själar i timmen',
    nextHint: 'Klara vågen en gång för att gå vidare. Klarade vågor upprepas tills du trycker på Nästa våg.',
    recruit: 'Rekrytera',
    upgrade: 'Uppgradera',
    upgradeTo: 'Uppgradera till {level}',
    place: 'Placera',
    move: 'Flytta',
    store: 'Plocka bort',
    buy: 'Köp',
    build: 'Bygg',
    cancel: 'Avbryt',
    close: 'Stäng',
    locked: 'Furstenivå {level}',
    stored: 'I förrådet',
    deployed: 'Utplacerad',
    dead: 'Kommer tillbaka nästa våg',
    army: 'Dina monster',
    shop: 'Rekrytera',
    slots: 'Platser',
    slotsOf: '{kind}: {used} / {max}',
    buySlot: '+1 plats',
    'kind.melee': 'Närstrid',
    'kind.ranged': 'Avstånd',
    'kind.wall': 'På muren',
    'kind.support': 'Bakom muren',
    'kind.trap': 'Fällor',
    placeHint: 'Tryck på en lysande ruta för att placera {name}.',
    aimHint: 'Tryck där Helveteseld ska slå ner.',
    cell: 'Rad {row}: {kind}',
    emptyCell: 'Inget här än.',
    fits: 'Placera här',
    'problem.slots': 'Ingen ledig plats: köp en till under {tab}.',
    'problem.noWall': 'Bygg muren först.',
    'problem.taken': 'Något står redan där.',
    'problem.souls': 'Inte tillräckligt med själar.',
    'm.orc': 'Orckrigare',
    'm.ogre': 'Troll',
    'm.imp': 'Imp',
    'm.skeleton': 'Skelettbågskytt',
    'm.shaman': 'Orcshaman',
    'm.necro': 'Nekromantiker',
    'md.orc': 'Närstrid, allround.',
    'md.ogre': 'Närstridstank, slår 2 hjältar.',
    'md.imp': 'Närstrid, mycket snabba attacker.',
    'md.skeleton': 'Avstånd, lång räckvidd.',
    'md.shaman': 'Avståndsmagi, saktar ner hjältar.',
    'md.necro': 'Avstånd, träffar runt målet.',
    's.ballista': 'Benballista',
    's.brazier': 'Helveteseldsfat',
    's.turret': 'Själatorn',
    's.altar': 'Blodaltare',
    's.drum': 'Krigstrumma',
    's.well': 'Själabrunn',
    's.spikes': 'Spikgrop',
    's.tar': 'Tjärpöl',
    's.bones': 'Benspikar',
    'sd.ballista': 'Långa skott mot en hjälte.',
    'sd.brazier': 'Bränner hjältar i ett litet område.',
    'sd.turret': 'En själablixt som hoppar till 3 hjältar.',
    'sd.altar': 'Helar muren och monstren.',
    'sd.drum': '+{n} % skada för hela din sida.',
    'sd.well': '+{n} % själar från dödade hjältar.',
    'sd.spikes': 'Skadar varje hjälte som går över.',
    'sd.tar': 'Hjältar i den går {n} % långsammare.',
    'sd.bones': 'Stoppar varje hjälte i {n} s.',
    wall: 'Muren',
    wallAbout: 'Håller hjältarna tillbaka. Avståndsmonster på den ökar dess hälsa. En raserad mur bygger upp sig själv på {n} s.',
    buildWall: 'Bygg muren',
    structures: 'Byggnader',
    owned: 'Dina',
    'sp.hellfire': 'Helveteseld',
    'sp.bonewall': 'Benmur',
    'sp.souldrain': 'Själasug',
    'spd.hellfire': 'Bränner alla hjältar där du trycker.',
    'spd.bonewall': 'Skyddar muren och frontlinjen.',
    'spd.souldrain': 'Suger 3 hjältar och helar din sida.',
    cast: 'Kasta',
    ready: 'Redo',
    autoCast: 'Kasta själv',
    on: 'På',
    off: 'Av',
    'r.fury': 'Raseri',
    'r.vigor': 'Livskraft',
    'r.haste': 'Snabbhet',
    'r.leech': 'Blodsug',
    'r.greed': 'Girighet',
    'r.thorns': 'Taggar',
    'rd.fury': '+{n} % skada',
    'rd.vigor': '+{n} % hälsa',
    'rd.haste': '+{n} % attackfart',
    'rd.leech': 'Helar {n} % av skadan den gör',
    'rd.greed': '+{n} % själar (var den än sitter)',
    'rd.thorns': 'Studsar {n} % av närstridsskadan',
    'rarity.0': 'Vanlig',
    'rarity.1': 'Sällsynt',
    'rarity.2': 'Episk',
    'rarity.3': 'Legendarisk',
    'rarity.4': 'Mytisk',
    runeName: '{type}, {rarity}',
    merge: 'Slå ihop 3',
    breakDown: 'Krossa (+{souls})',
    noRunes: 'Inga runor än. Hjältar tappar dem ibland, och bossar alltid.',
    runeSlots: 'Runor',
    runeSlotLocked: 'Öppnas på nivå {level}',
    emptySlot: 'Tom',
    chooseRune: 'Välj en runa',
    unequip: 'Ta av',
    equippedOn: 'På: {who}',
    learn: 'Lär',
    tapTalent: 'Tryck på en talang för att se vad den gör.',
    inventory: 'Förråd',
    'ts.lordDmg': 'Furstens skada',
    'ts.cooldown': 'Väntetider',
    'ts.burn': 'Brinnande mark',
    'ts.bossReset': 'Bossåterställ',
    'ts.monsterHp': 'Monsterhälsa',
    'ts.monsterDmg': 'Monsterskada',
    'ts.recruitCost': 'Billiga monster',
    'ts.slotCost': 'Billiga platser',
    'ts.souls': 'Fler själar',
    'ts.runeDrop': 'Runfynd',
    'ts.offline': 'Bortatid',
    'ts.mergeRefund': 'Återbäring',
    'ts.wallHp': 'Murhälsa',
    'ts.rebuild': 'Snabbt återbygge',
    'ts.structCost': 'Billigt bygge',
    'ts.trapDmg': 'Fällskada',
    talents: 'Talanger',
    points: 'Poäng: {n}',
    'b.tyranny': 'Tyranni',
    'b.legion': 'Legion',
    'b.greed': 'Girighet',
    'b.fortress': 'Fästning',
    't.lordDmg': '+5 % furstens skada',
    't.cooldown': '−5 % väntetid för besvärjelser',
    't.burn': 'Helveteseld lämnar brinnande mark',
    't.bossReset': 'Dödade bossar nollställer väntetiderna',
    't.monsterHp': '+5 % monstrens hälsa',
    't.monsterDmg': '+5 % monstrens skada',
    't.recruitCost': '−10 % kostnad för rekrytering och uppgradering',
    't.slotCost': '−20 % kostnad för platser',
    't.souls': '+5 % själar',
    't.runeDrop': '+1 % chans att hitta runor',
    't.offline': '+2 h gräns när spelet är stängt',
    't.mergeRefund': 'Ibland får du tillbaka en runa när du slår ihop',
    't.wallHp': '+8 % murens hälsa',
    't.rebuild': '−10 % tid att bygga upp muren',
    't.structCost': '−10 % kostnad för byggnader',
    't.trapDmg': 'Fällor skadar 50 % mer',
    away: 'Medan du var borta',
    awayText: 'Dina monster höll våg {wave} i {time}.',
    awaySouls: '+{n} själar',
    awayXp: '+{n} XP',
    awayRunes: '+{n} runor',
    awayLevels: 'Demonfursten gick upp {n} nivåer.',
    hours: '{h} h {m} min',
    minutes: '{m} min',
  },
});

// Big numbers stay short: 12,480 → 12.5k.
export function fmt(n) {
  n = Math.floor(n);
  if (n < 10000) return n.toLocaleString('en-US');
  const units = ['k', 'M', 'B', 'T'];
  let i = -1;
  while (n >= 1000 && i < units.length - 1) {
    n /= 1000;
    i += 1;
  }
  return `${n >= 100 ? Math.round(n) : n.toFixed(1)}${units[i]}`;
}
