import { makeT } from '../../../shared/i18n.js';

export const tr = makeT({
  en: {
    wood: 'Wood',
    stone: 'Stone',
    food: 'Food',
    gold: 'Gold',
    people: 'People',
    level: 'Level {n}',
    build: 'Build',
    upgrade: 'Upgrade',
    repair: 'Repair',
    train: 'Train',
    send: 'Send party',
    close: 'Close',
    units: 'Army',
    selectAll: 'Select all',
    moveHint: 'Tap where they should go.',
    buildHint: 'Tap an empty tile next to your town to build.',
    nothingHere: 'Nothing to build here.',
    underConstruction: 'Being built: {s}',
    upgrading: 'Upgrading: {s}',
    destroyed: 'Destroyed. Repair it to use it again.',
    maxLevel: 'Fully upgraded',
    produces: 'Makes {list} per minute',
    workers: 'Needs {n} workers',
    housing: 'Houses {n} people',
    storageCap: 'Stores up to {n} of each resource',
    towerInfo: 'Shoots monsters within {n} tiles',
    queue: 'Training: {list}',
    hp: 'Health {hp}/{max}',
    nextWave: 'Monsters in {time}',
    waveNow: 'Wave {n}: monsters are coming!',
    quiet: 'Quiet times',
    welcomeBack: 'While you were away ({time}):',
    built: '{name} is ready.',
    upgraded: '{name} reached level {n}.',
    trained: 'A {name} is ready.',
    lostBuilding: 'Monsters destroyed your {name}!',
    unitDied: 'Your {name} fell.',
    dungeonWon: 'Your party cleared {name}! Loot: {loot}',
    dungeonLost: 'Your party failed in {name}. {back} came back.',
    dungeonName: 'Dungeon (tier {n})',
    dungeonReady: 'Send units in. They come back after {s} with loot, if they win.',
    dungeonRunning: 'Party inside, back in {s}',
    dungeonCooldown: 'Being restocked: {s}',
    chance: 'Chance to win: {n}%',
    pickParty: 'Pick who goes:',
    noIdle: 'No units free. Train some first.',
    newGame: 'Start a new island',
    newGameTitle: 'Start over?',
    newGameMessage: 'Your whole island, buildings and army will be lost.',
    newGameYes: 'Start over',
    // why a building can't go somewhere
    hidden: 'You haven’t explored there yet.',
    occupied: 'That tile is taken.',
    tooFar: 'Too far from your town.',
    noWorkers: 'Not enough people. Build homes.',
    noPeople: 'Not enough people. Build homes.',
    noResources: 'Not enough resources.',
    busy: 'Busy right now.',
    queueFull: 'Training queue is full.',
    terrain_farm: 'Farms go on grass.',
    terrain_mine: 'Mines go on hills.',
    terrain_windmill: 'Windmills go on grass.',
    terrain_tower: 'Towers can’t go there.',
    terrain_home: 'Build on grass or forest.',
    terrain_market: 'Build on grass or forest.',
    terrain_barracks: 'Build on grass or forest.',
    terrain_archery: 'Build on grass or forest.',
    terrain_chapel: 'Build on grass or forest.',
    terrain_tavern: 'Build on grass or forest.',
    terrain_blacksmith: 'Build on grass or forest.',
    terrain_lumbermill: 'Build on grass or forest.',
    terrain_watermill: 'Build on grass or forest.',
    near_forest: 'Needs forest next to it.',
    near_water: 'Needs water next to it.',
    // names
    b_blacksmith: 'Blacksmith',
    r_weapons: 'Weapons',
    r_armour: 'Armour',
    researchCard: '{name} {tier}',
    researchInfo: 'Weapons {w}/3 (+{wp}% damage), armour {a}/3 (+{ap}% health) for every unit.',
    researching: 'Researching {name}: {s}',
    researched: '{name} {tier} is ready: all units are stronger.',
    levelUp: '{name} reached level {n}!',
    heroLine: '{name}, {type}, level {n}',
    xpLine: 'Health {hp}/{max} · {xp} XP',
    b_catapult: 'Catapult tower',
    m_titan: 'Stone titan',
    bossWave: 'A stone titan leads wave {n}!',
    b_tavern: 'Tavern',
    tavernInfo: 'Every home holds {n} more people',
    trade: 'Trade',
    give: 'Give',
    get: 'Get',
    tradeButton: 'Trade {give} for {get}',
    traded: 'Traded for {n} {res}.',
    goals: 'Goals',
    goalsTitle: 'Goals ({n}/{max})',
    goalDone: 'Goal reached: {name}. Reward: {reward}',
    reward: 'Reward: {reward}',
    g_homes: 'Build 2 homes',
    g_farm: 'Grow food: build a farm or a mill',
    g_wood: 'Build a lumber mill',
    g_stone: 'Build a mine on a hill',
    g_army: 'Have 3 units',
    g_kills: 'Defeat 10 monsters',
    g_dungeon: 'Clear a dungeon',
    g_research: 'Research at the blacksmith',
    g_castle: 'Upgrade the castle',
    g_hero: 'Get a hero to level 3',
    g_wave5: 'Beat wave 5',
    g_people: 'Have homes for 30 people',
    g_deep: 'Clear a tier 3 dungeon',
    g_titan: 'Defeat a stone titan',
    b_wall: 'Wall',
    b_gate: 'Gate',
    wallInfo: 'Monsters can\u2019t pass; they break through if there\u2019s no other way.',
    gateInfo: 'Your units walk through; monsters can\u2019t.',
    b_castle: 'Castle',
    b_home: 'Home',
    b_farm: 'Farm',
    b_lumbermill: 'Lumber mill',
    b_mine: 'Mine',
    b_windmill: 'Windmill',
    b_watermill: 'Watermill',
    b_market: 'Market',
    b_barracks: 'Barracks',
    b_archery: 'Archery range',
    b_chapel: 'Chapel',
    b_tower: 'Tower',
    u_knight: 'Knight',
    u_barbarian: 'Barbarian',
    u_rogue: 'Crossbow rogue',
    u_scout: 'Scout',
    u_mage: 'Mage',
    m_slime: 'Slime',
    m_spirit: 'Skull spirit',
    m_golem: 'Rock golem',
  },
  sv: {
    wood: 'Trä',
    stone: 'Sten',
    food: 'Mat',
    gold: 'Guld',
    people: 'Folk',
    level: 'Nivå {n}',
    build: 'Bygg',
    upgrade: 'Uppgradera',
    repair: 'Reparera',
    train: 'Träna',
    send: 'Skicka grupp',
    close: 'Stäng',
    units: 'Armé',
    selectAll: 'Välj alla',
    moveHint: 'Tryck där de ska gå.',
    buildHint: 'Tryck på en tom ruta nära staden för att bygga.',
    nothingHere: 'Här går inget att bygga.',
    underConstruction: 'Byggs: {s}',
    upgrading: 'Uppgraderas: {s}',
    destroyed: 'Förstörd. Reparera den för att använda den igen.',
    maxLevel: 'Fullt uppgraderad',
    produces: 'Ger {list} per minut',
    workers: 'Behöver {n} arbetare',
    housing: 'Rymmer {n} personer',
    storageCap: 'Lagrar upp till {n} av varje resurs',
    towerInfo: 'Skjuter monster inom {n} rutor',
    queue: 'Tränar: {list}',
    hp: 'Hälsa {hp}/{max}',
    nextWave: 'Monster om {time}',
    waveNow: 'Våg {n}: monster är på väg!',
    quiet: 'Lugna tider',
    welcomeBack: 'Medan du var borta ({time}):',
    built: '{name} är klar.',
    upgraded: '{name} nådde nivå {n}.',
    trained: 'En {name} är redo.',
    lostBuilding: 'Monster förstörde din {name}!',
    unitDied: 'Din {name} föll.',
    dungeonWon: 'Gruppen rensade {name}! Byte: {loot}',
    dungeonLost: 'Gruppen misslyckades i {name}. {back} kom tillbaka.',
    dungeonName: 'Grotta (nivå {n})',
    dungeonReady: 'Skicka in enheter. De kommer tillbaka efter {s} med byte, om de vinner.',
    dungeonRunning: 'Gruppen är inne, tillbaka om {s}',
    dungeonCooldown: 'Fylls på: {s}',
    chance: 'Chans att vinna: {n}%',
    pickParty: 'Välj vilka som går:',
    noIdle: 'Inga lediga enheter. Träna några först.',
    newGame: 'Börja på en ny ö',
    newGameTitle: 'Börja om?',
    newGameMessage: 'Hela din ö, alla byggnader och hela armén försvinner.',
    newGameYes: 'Börja om',
    hidden: 'Du har inte utforskat där än.',
    occupied: 'Rutan är upptagen.',
    tooFar: 'För långt från staden.',
    noWorkers: 'Inte tillräckligt med folk. Bygg hem.',
    noPeople: 'Inte tillräckligt med folk. Bygg hem.',
    noResources: 'Inte tillräckligt med resurser.',
    busy: 'Upptagen just nu.',
    queueFull: 'Träningskön är full.',
    terrain_farm: 'Gårdar byggs på gräs.',
    terrain_mine: 'Gruvor byggs på kullar.',
    terrain_windmill: 'Väderkvarnar byggs på gräs.',
    terrain_tower: 'Torn kan inte stå där.',
    terrain_wall: 'Murar byggs på gräs, skog eller kullar.',
    terrain_gate: 'Portar byggs på gräs, skog eller kullar.',
    terrain_catapult: 'Torn kan inte stå där.',
    terrain_home: 'Bygg på gräs eller skog.',
    terrain_market: 'Bygg på gräs eller skog.',
    terrain_barracks: 'Bygg på gräs eller skog.',
    terrain_archery: 'Bygg på gräs eller skog.',
    terrain_chapel: 'Bygg på gräs eller skog.',
    terrain_tavern: 'Bygg på gräs eller skog.',
    terrain_blacksmith: 'Bygg på gräs eller skog.',
    terrain_lumbermill: 'Bygg på gräs eller skog.',
    terrain_watermill: 'Bygg på gräs eller skog.',
    near_forest: 'Behöver skog bredvid.',
    near_water: 'Behöver vatten bredvid.',
    b_blacksmith: 'Smedja',
    r_weapons: 'Vapen',
    r_armour: 'Rustning',
    researchCard: '{name} {tier}',
    researchInfo: 'Vapen {w}/3 (+{wp}% skada), rustning {a}/3 (+{ap}% hälsa) för alla enheter.',
    researching: 'Forskar på {name}: {s}',
    researched: '{name} {tier} är klar: alla enheter är starkare.',
    levelUp: '{name} nådde nivå {n}!',
    heroLine: '{name}, {type}, nivå {n}',
    xpLine: 'Hälsa {hp}/{max} · {xp} XP',
    b_catapult: 'Katapulttorn',
    m_titan: 'Stentitan',
    bossWave: 'En stentitan leder våg {n}!',
    b_tavern: 'Krog',
    tavernInfo: 'Varje hem rymmer {n} fler personer',
    trade: 'Byt',
    give: 'Ge',
    get: 'Få',
    tradeButton: 'Byt {give} mot {get}',
    traded: 'Du fick {n} {res}.',
    goals: 'Mål',
    goalsTitle: 'Mål ({n}/{max})',
    goalDone: 'Mål klart: {name}. Belöning: {reward}',
    reward: 'Belöning: {reward}',
    g_homes: 'Bygg 2 hem',
    g_farm: 'Odla mat: bygg en gård eller kvarn',
    g_wood: 'Bygg ett sågverk',
    g_stone: 'Bygg en gruva på en kulle',
    g_army: 'Ha 3 enheter',
    g_kills: 'Besegra 10 monster',
    g_dungeon: 'Rensa en grotta',
    g_research: 'Forska i smedjan',
    g_castle: 'Uppgradera borgen',
    g_hero: 'Få en hjälte till nivå 3',
    g_wave5: 'Klara våg 5',
    g_people: 'Ha hem för 30 personer',
    g_deep: 'Rensa en grotta på nivå 3',
    g_titan: 'Besegra en stentitan',
    b_wall: 'Mur',
    b_gate: 'Port',
    wallInfo: 'Monster kommer inte förbi; de slår sig igenom om det inte finns någon annan väg.',
    gateInfo: 'Dina enheter går igenom; monster kan inte.',
    b_castle: 'Borg',
    b_home: 'Hem',
    b_farm: 'Gård',
    b_lumbermill: 'Sågverk',
    b_mine: 'Gruva',
    b_windmill: 'Väderkvarn',
    b_watermill: 'Vattenkvarn',
    b_market: 'Marknad',
    b_barracks: 'Kasern',
    b_archery: 'Skjutbana',
    b_chapel: 'Kapell',
    b_tower: 'Torn',
    u_knight: 'Riddare',
    u_barbarian: 'Barbar',
    u_rogue: 'Armborstskytt',
    u_scout: 'Spejare',
    u_mage: 'Magiker',
    m_slime: 'Slem',
    m_spirit: 'Skalleande',
    m_golem: 'Stengolem',
  },
});
